[build]
  publish = "public"
  functions = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"